version: 1
formatters:
  basic_format:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
handlers:
  stream:
    class: logging.StreamHandler
    level: INFO
    formatter: basic_format
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: DEBUG
    formatter: basic_format
    filename: 'log/application.log' # Replace your log file path here
    encoding: utf8
    mode: a
loggers:
  app:
    level: DEBUG
    handlers: [stream, file]
    propagate: no
  sqlalchemy:
    level: DEBUG
    handlers: [stream, file]
    propagate: no
root:
  level: DEBUG
  handlers: [stream, file]